stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_REGISTRY_BASE: $CI_REGISTRY_IMAGE
  DOCKER_TLS_CERTDIR: "/certs"
  SWARM_FOLDER: /mnt/cephfs/swarm/stacks/cal.minet.net
  DOCKER_BUILDKIT: 1

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - |
    if [ "$CI_COMMIT_REF_NAME" = "$CI_DEFAULT_BRANCH" ]; then
      export IMAGE_TAG=stable
    else
      export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    fi

build_backend:
  stage: build
  image: docker:latest
  rules:
    - changes:
        - backend/**/*
  script:
    - cd backend
    - docker pull $IMAGE_REGISTRY_BASE/backend:$IMAGE_TAG || true
    - docker build --cache-from $IMAGE_REGISTRY_BASE/backend:$IMAGE_TAG --build-arg BUILDKIT_INLINE_CACHE=1 -f Dockerfile.prod -t $IMAGE_REGISTRY_BASE/backend:$IMAGE_TAG .
    - docker push $IMAGE_REGISTRY_BASE/backend:$IMAGE_TAG

build_nginx:
  stage: build
  image: docker:latest
  rules:
    - changes:
        - frontend/**/*
        - nginx/**/*
  script:
    - docker pull $IMAGE_REGISTRY_BASE/nginx:$IMAGE_TAG || true
    - docker build --cache-from $IMAGE_REGISTRY_BASE/nginx:$IMAGE_TAG --build-arg BUILDKIT_INLINE_CACHE=1 -f nginx/Dockerfile -t $IMAGE_REGISTRY_BASE/nginx:$IMAGE_TAG .
    - docker push $IMAGE_REGISTRY_BASE/nginx:$IMAGE_TAG

build_media_processor:
  stage: build
  image: docker:latest
  rules:
    - changes:
        - media-processor/**/*
  script:
    - cd media-processor
    - docker pull $IMAGE_REGISTRY_BASE/media-processor:$IMAGE_TAG || true
    - docker build --cache-from $IMAGE_REGISTRY_BASE/media-processor:$IMAGE_TAG --build-arg BUILDKIT_INLINE_CACHE=1 -f Dockerfile -t $IMAGE_REGISTRY_BASE/media-processor:$IMAGE_TAG .
    - docker push $IMAGE_REGISTRY_BASE/media-processor:$IMAGE_TAG

deploy:
  stage: deploy
  trigger:
    project: minet/configurations/push/swarm-prod
    branch: main
    strategy: depend
    inputs:
      folder_name: cal.minet.net
      image_registry: $CI_REGISTRY_IMAGE
  needs:
    - job: build_backend
      optional: true
    - job: build_nginx
      optional: true
    - job: build_media_processor
      optional: true
  only:
    - main
