version: "3.8"

services:
  nginx:
    image: ${IMAGE_REGISTRY_BASE}/nginx:stable
    ports:
      - 8001:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - backend
    environment:
      - WAIT_FOR_SERVICES=backend:8000 minio:9000
    networks:
      - calendint_net

  backend:
    image: ${IMAGE_REGISTRY_BASE}/backend:stable
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/calendint
      - CAMPUS_CLIENT_ID=${CAMPUS_CLIENT_ID}
      - CAMPUS_CLIENT_SECRET=${CAMPUS_CLIENT_SECRET}
      - CAMPUS_METADATA_URL=${CAMPUS_METADATA_URL}
      - CAS_SERVER_URL=${CAS_SERVER_URL}
      - CAS_PROTOCOL=${CAS_PROTOCOL}
      - APP_BASE_URL=${APP_BASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_SECURE=false
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_NAME=${EMAILS_FROM_NAME}
    volumes:
      - ${VOLUMES}/cal.minet.net/migration_state:/app/migration_state
    deploy:
      replicas: 1
    depends_on:
      - db
      - minio
    networks:
      - calendint_net

  db:
    image: postgres:15
    volumes:
      - ${VOLUMES}/cal.minet.net/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=calendint
    deploy:
      replicas: 1
    networks:
      - calendint_net

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - ${VOLUMES}/cal.minet.net/minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    deploy:
      replicas: 1
    networks:
      - calendint_net

networks:
  calendint_net:
    driver: overlay
